[2023-10-05T20:04:29.922+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-10-05T20:04:26.861808+00:00 [queued]>
[2023-10-05T20:04:29.934+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-10-05T20:04:26.861808+00:00 [queued]>
[2023-10-05T20:04:29.935+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-10-05T20:04:29.936+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-10-05T20:04:29.937+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-10-05T20:04:29.955+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-10-05 20:04:26.861808+00:00
[2023-10-05T20:04:29.962+0000] {standard_task_runner.py:55} INFO - Started process 1312 to run task
[2023-10-05T20:04:29.967+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2023-10-05T20:04:26.861808+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpbb5_4a92']
[2023-10-05T20:04:29.970+0000] {standard_task_runner.py:83} INFO - Job 31: Subtask is_api_available
[2023-10-05T20:04:30.050+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available manual__2023-10-05T20:04:26.861808+00:00 [running]> on host ca408aed2033
[2023-10-05T20:04:30.167+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-10-05T20:04:26.861808+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-05T20:04:26.861808+00:00
[2023-10-05T20:04:30.169+0000] {http.py:120} INFO - Poking: api/
[2023-10-05T20:04:30.180+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2023-10-05T20:04:30.182+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-10-05T20:04:30.397+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2023-10-05T20:04:30.412+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20231005T200426, start_date=20231005T200429, end_date=20231005T200430
[2023-10-05T20:04:30.468+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-10-05T20:04:30.518+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
