[2023-10-05T20:10:51.715+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-10-05T20:10:49.482404+00:00 [queued]>
[2023-10-05T20:10:51.726+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-10-05T20:10:49.482404+00:00 [queued]>
[2023-10-05T20:10:51.727+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-10-05T20:10:51.727+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-10-05T20:10:51.728+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-10-05T20:10:51.742+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-10-05 20:10:49.482404+00:00
[2023-10-05T20:10:51.749+0000] {standard_task_runner.py:55} INFO - Started process 1638 to run task
[2023-10-05T20:10:51.754+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2023-10-05T20:10:49.482404+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp2cwiva7d']
[2023-10-05T20:10:51.760+0000] {standard_task_runner.py:83} INFO - Job 41: Subtask is_api_available
[2023-10-05T20:10:51.843+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available manual__2023-10-05T20:10:49.482404+00:00 [running]> on host ca408aed2033
[2023-10-05T20:10:51.925+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-10-05T20:10:49.482404+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-05T20:10:49.482404+00:00
[2023-10-05T20:10:51.927+0000] {http.py:120} INFO - Poking: api/
[2023-10-05T20:10:51.938+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2023-10-05T20:10:51.940+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-10-05T20:10:52.141+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2023-10-05T20:10:52.152+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20231005T201049, start_date=20231005T201051, end_date=20231005T201052
[2023-10-05T20:10:52.208+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-10-05T20:10:52.254+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
