[2023-09-28T19:47:16.722+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-09-28T19:47:14.081667+00:00 [queued]>
[2023-09-28T19:47:16.794+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-09-28T19:47:14.081667+00:00 [queued]>
[2023-09-28T19:47:16.795+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-09-28T19:47:16.797+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-09-28T19:47:16.798+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-09-28T19:47:16.835+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-09-28 19:47:14.081667+00:00
[2023-09-28T19:47:16.869+0000] {standard_task_runner.py:55} INFO - Started process 5917 to run task
[2023-09-28T19:47:16.883+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2023-09-28T19:47:14.081667+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp7lve0o1m']
[2023-09-28T19:47:16.889+0000] {standard_task_runner.py:83} INFO - Job 17: Subtask is_api_available
[2023-09-28T19:47:17.128+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available manual__2023-09-28T19:47:14.081667+00:00 [running]> on host d9ce0052adca
[2023-09-28T19:47:17.324+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-09-28T19:47:14.081667+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-28T19:47:14.081667+00:00
[2023-09-28T19:47:17.327+0000] {http.py:120} INFO - Poking: api/
[2023-09-28T19:47:17.357+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2023-09-28T19:47:17.414+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-09-28T19:47:17.809+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2023-09-28T19:47:17.850+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20230928T194714, start_date=20230928T194716, end_date=20230928T194717
[2023-09-28T19:47:17.909+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-09-28T19:47:17.971+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
